### ISSUE TITLE
Supporting native markdown

### ISSUE THREAD

**Issue by mamichels** [telegramdesktop/tdesktop#5960]
### Feature Request: Native support for markdown
Guess we would all agree that the markdown abbreviations in telegram derivate to much from the semi official but well established syntax. 

<br>

### Issue
While the current syntax may works it is neither complete nor supports an adequat user experience when for example copying md into the chat.

<br>

### Required Changes
I plead to at least have the following changes

- Change syntax of *italic* to asterix
- Adding the support of Headings (#, ##, ### ...)
- Adding the support of blockquotes (>)
- Adding the support of ordered lists (1., 2., 3. ...)
- Adding the support of unordered lists (-)
- Adding the support of horizontal rules (---)
- Adding the support of inline links ([link] (http...))

Optional syntax like tables, footnotes or definitions would be great.

<br>

---
### Roadmap
- [x] Identified a critical issue
- [x] Wrote a qualified Feature Request
- [ ] Submitted a Pull Request

<br>

> also see issue#1842 on the [webclient](https://github.com/zhukov/webogram/issues/1842)
> proudly formated with markdown

**Comment by SmartManoj** [comment]
Why it should not be done client side ?
