### ISSUE TITLE
i (don't) like the new font meta thread

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#7851]
Well, some people likes the new font, some no for now we have:

- [ ] persian https://github.com/telegramdesktop/tdesktop/issues/7840
- [ ] armenian https://github.com/telegramdesktop/tdesktop/issues/7849
- [ ] thai https://github.com/telegramdesktop/tdesktop/issues/7845

ilya-fedin is trying to get one proper font for every user of those languages.

**Comment by Aokromes** [comment]
vote here up if you like new persian font, vote don't if you don't

**Comment by Aokromes** [comment]
vote here up if you like new armenian font, vote don't if you don't

**Comment by Aokromes** [comment]
vote here up if you like new thai font, vote don't if you don't

**Comment by Aokromes** [comment]
reserved 1

**Comment by Aokromes** [comment]
reserved 2

**Comment by Aokromes** [comment]
reserved 3

**Comment by Aokromes** [comment]
reserved 4

**Comment by ilya-fedin** [comment]
> vote here up if you like new armenian font, vote don't if you don't

New armenian & thai font is not intentional, that's a bug
